from django.core.exceptions import ValidationError


class ContainsLetterValidator:
    def validate(self,password, user=None):
       pass

    def get_help_text(self):
        pass